### ISSUE TITLE
Binding is not always BINDING_HTTP_POST

### ISSUE THREAD

**Issue by dhrp** [OTA-Insight/djangosaml2idp#10]
https://github.com/OTA-Insight/djangosaml2idp/blob/master/djangosaml2idp/views.py#L68

djangosaml2idp (naively?) seems to assume the type is always BINDING_HTTP_POST (and not BINDING_HTTP_REDIRECT). This causes the mechanism to fail when the request is deflated (compressed), as the pysaml library uses that parameter to decide whether to deflate the request or not. 

This probably has something to do with this line in code:
```
# TODO Add http redirect logic based on https://github.com/rohe/pysaml2/blob/master/example/idp2_repoze/idp.py#L327
```
But I think it's worth mentioning here that I ran into this issue.

**Comment by Skylude** [comment]
I got this same issue and I added some custom logic to my login controller to basically deflate it so it would work later in the login process.

**Comment by mhindery** [comment]
You are correct that it only supports the Post binding. This package was made when we needed to implement an internal SSO flow, and we opted for the post flow. As we do not use the Redirect type, there wasn't any need for it and I never invested time in adding it. However, good news! This PR https://github.com/OTA-Insight/djangosaml2idp/pull/19 adds support for the Redirect type.

**Comment by mhindery** [comment]
The latest release adds support for the Redirect binding:  https://github.com/OTA-Insight/djangosaml2idp/releases
