### ISSUE TITLE
Assersion Signature Verification

### ISSUE THREAD

**Issue by HacKeD0x90** [OTA-Insight/djangosaml2idp#104]
Hello can you point me on where exactly in the example project , the signature verification on the SAMLResponse content is being done?
I know you are using xmlsecurity but can't identify where this check is done in the code, i only find the import of xmlsec in settings.py

Thanks

**Comment by peppelinux** [comment]
We have It in pysaml2 internals, look at there

**Comment by HacKeD0x90** [comment]
so if i understand correctly , the code is not here in this repository?

**Comment by peppelinux** [comment]
Yes sir, It's in pysaml2
