### ISSUE TITLE
IndexError at /saml2/login/

### ISSUE THREAD

**Issue by stodge** [OTA-Insight/djangosaml2idp#13]
I tried using your examples in Docker but when I clicked "Login" I got the following error. Was I supposed to configure the SP? I assumed it was already configured. Thanks

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/saml2/login/

Django Version: 1.11.13
Python Version: 2.7.14
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'djangosaml2']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/lib/python2.7/site-packages/djangosaml2/views.py" in login
  148.     supported_bindings = get_idp_sso_supported_bindings(selected_idp, config=conf)

File "/usr/lib/python2.7/site-packages/djangosaml2/utils.py" in get_idp_sso_supported_bindings
  49.         idp_entity_id = list(available_idps(config).keys()).pop()

Exception Type: IndexError at /saml2/login/
Exception Value: pop from empty list
```

**Comment by fleonasb** [comment]
If you update djdangosaml2 to v0.16.11, such version got a [patch](https://github.com/knaperek/djangosaml2/commit/480fb884fbb32e3c1127307ed4d1729ed674ca11) that clearly says there's no IdP configured:

> djangosaml2idp_sp | Traceback (most recent call last):
djangosaml2idp_sp |   File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
djangosaml2idp_sp |     response = get_response(request)
djangosaml2idp_sp |   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
djangosaml2idp_sp |     response = self.process_exception_by_middleware(e, request)
djangosaml2idp_sp |   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
djangosaml2idp_sp |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
djangosaml2idp_sp |   File "/usr/lib/python2.7/site-packages/djangosaml2/views.py", line 156, in login
djangosaml2idp_sp |     supported_bindings = get_idp_sso_supported_bindings(selected_idp, config=conf)
djangosaml2idp_sp |   File "/usr/lib/python2.7/site-packages/djangosaml2/utils.py", line 56, in get_idp_sso_supported_bindings
djangosaml2idp_sp |     raise ImproperlyConfigured("No IdP configured!")
djangosaml2idp_sp | ImproperlyConfigured: No IdP configured!

but, as far as I know... the example is already configured (?).

**Comment by mhindery** [comment]
Hi @stodge @fleonasb the example project has been updated with the current Python 3 and Django 2.x versions and they now should work out of the box again.
