### ISSUE TITLE
[Additional feature] User definitions and attributes from different sources

### ISSUE THREAD

**Issue by peppelinux** [OTA-Insight/djangosaml2idp#24]
There would be the possibility to get users attributes from different sources, different Databases.
Actually the User is authenticated through the available Django Auth backends and then its identity and attributes will be fetched from the USER model as default, after that they have been saved as a new instance or updated as well. This is a quite common scenario.

In my case I have to deal with LDAP user definitions, throught this:
https://github.com/peppelinux/django-ldap-academia-ou-manager

I'm thinnking about a custom Processor, I'm also asking here if there would be the need of some more examples in the Documentation, just to show that "Yes, It can do ALSO this!". 
An idea could be represented as follow

````
SAML_IDP_SPCONFIG = {
    'http://localhost:8000/saml2/metadata/': {
        'processor': 'djangosaml2idp.processors.BaseProcessor',
        'attribute_mapping': {
            # DJANGO: SAML
            'is_staff': 'is_staff',
            'is_superuser': 'is_superuser',
            'email': {'name': 'get_last_email', 'from': 'ldap_peoples.models.LdapAcademiaUser', 'lookup': ('email', '__in', 'emails')}
            'first_name': {'name': 'first_name', 'from': '$app_name.models.$ModelName', rewrite_rules: [all_lowercase, ], 'lookup': ('username', '__iexact', 'username') }
            'last_name':  {'name': 'last_name', 'from': '$app_name.models.$ModelName', rewrite_rules: [all_lowercase, ], 'lookup': ('username', '__iexact', 'nameid') }
            'eppn': {'name': 'eduPersonPrincipalName', 'from': 'ldap_peoples.models.LdapAcademiaUser', rewrite_rules: [add_scoped_org_name, ],  'lookup': ('username', '__iexact', 'uid') }
            'givenName':  {'rewrite_rules': [name_surname_concat, as_title] }
        }
    }
}
````
Where:
`from:` could be the Model where to get this attribute
`name:` could be a field name, or a class method or a property of the `from:` model name. This could help us to define a specilized method to gathering something more regarding 1-to-Many and FK relationships.
`rewrite_rules`: a list of concatenated rewrite functions that takes all the attributes to clean, modify, concatenate and do whatever action over them then returning the one (it could be also a list() in SAML context)
`lookup`: a tuple containing (USER field name, 'exact_to', 'Destination app.model.field_name')

Also see that we have legacy definitions as `'is_staff': 'is_staff',`, so the Processors then have to check if that mapping is a string or a dictionary and deal with the easy or the complex way.

The Processor could have also to recheck pysaml2 config policies to prevent that a rewrite rule could bypass one of these. 

Probably defining a custom method in the model would be more easy to deal with, instead of complex mapping definitions. I already talked about attr_rewrite rules [here](https://github.com/OTA-Insight/djangosaml2idp/issues/22)

**Comment by askvortsov1** [comment]
Hi!

I think an easier solution might be adding callable support to the default processor. This would allow us to use getter methods as well as regular attributes in our Django Auth User model. As of right now, property methods can be used for the same effect (although this isn't really Pythonic). I think that allowing methods would be simpler and more customizable than trying to handle all this data fetching within the SP attribute mapping. Similarly, you would be able to implement any rewriting as needed with these methods, so this would solve this issue as well. What do you think?

**Comment by peppelinux** [comment]
I think that you're right, that mapping seems too complex. Custom processor Is the answer, the method that return the attr dictionary Is the Key. What about the callable support are you tried to tell us? It seems interesting

**Comment by askvortsov1** [comment]
So essentially, instead of just adding all attributes from the user class, it calls any that are callable. I just added this to my open pull request. That being said, if this solution is satisfactory, we can probably close this ticket. If not, please let me know and we can keep working towards a functional solution.

**Comment by peppelinux** [comment]
https://github.com/OTA-Insight/djangosaml2idp/commit/5431feebb0885fe255ab3df535a4a442c79c16dc

Got It, very good

**Comment by peppelinux** [comment]
I think that this should be closed with some examples in documentation. I'll do some with ldapdb about my use case. I'm not the owner of this repository but a contributor like you. Having an eye over your code I think that this project could have a good milestone for the future

**Comment by askvortsov1** [comment]
I added an example in documentation in 81aac04

**Comment by peppelinux** [comment]
Great, this could also help us to get a PersistentID from our DB, using a method. PersistentID must be generated at one time and must keeped persistent. A method to retrieve this will be very usefull.

All this looks pretty good, I'll move forward to implement SLO before returning on attr rewrite and fetching attrs from multiple sources/db like LDAP and others.
