### ISSUE TITLE
[Security] TODO verify signature

### ISSUE THREAD

**Issue by peppelinux** [OTA-Insight/djangosaml2idp#25]
In [views.LoginProcessView](https://github.com/OTA-Insight/djangosaml2idp/blob/master/djangosaml2idp/views.py#L124) we can read

````
        if "SigAlg" in request.session and "Signature" in request.session:
            _certs = self.IDP.metadata.certs(req_info.message.issuer.text, "any", "signing")
            verified_ok = False
            for cert in _certs:
                # TODO implement
                # if verify_redirect_signature(_info, self.IDP.sec.sec_backend, cert):
                #    verified_ok = True
                #    break
````
Should we have to deal with pySAML2 internals to validate the signature or should we have to code a specialized function to do this?

**Comment by peppelinux** [comment]
Fixed in https://github.com/peppelinux/djangosaml2idp/commit/a2beefb53e676b2d7eb180cc79b316d2bbb158ca
I made a [Pull Request]( https://github.com/askvortsov1/djangosaml2idp/pull/1) to @askvortsov1 because I'm coding on top of its commits. Hope to see a good double checking and a merge of all of this.

**Comment by peppelinux** [comment]
I think to get metadata certificates related ti an SP then check with these in every saml request

**Comment by askvortsov1** [comment]
I agree about tests to simulate real SAMLRequests coming in. Let's take a look at some python SAML client libraries that we might be able to extract SAMLRequest generation from.

**Comment by askvortsov1** [comment]
I'm opening up a new Issue to discuss testing further at https://github.com/OTA-Insight/djangosaml2idp/issues/27 so that we can stay on topic here.

**Comment by peppelinux** [comment]
Further readings here

https://github.com/IdentityPython/pysaml2/issues/594
https://github.com/IdentityPython/pysaml2/issues/592
https://github.com/IdentityPython/pysaml2/issues/579
https://github.com/IdentityPython/pysaml2/issues/344

**Comment by peppelinux** [comment]
Default IDP config is:
('only_use_keys_in_metadata', True)

so it should use metadata keys for validation!
TODO: check this with unit test

**Comment by peppelinux** [comment]
Tested verification in pySAML2, now I'm more relaxed about this security aspect.
I simply modified sp certs without updating them idp side.

````
returncode=1
error=func=xmlSecOpenSSLX509StoreVerify:file=x509vfy.c:line=347:obj=x509-store:subj=unknown:error=71:certificate verification failed:X509_verify_cert: subject=/CN=sp1.testunical.it; issuer=/CN=sp1.testunical.it; err=18; msg=self signed certificate
func=xmlSecOpenSSLX509StoreVerify:file=x509vfy.c:line=386:obj=x509-store:subj=unknown:error=71:certificate verification failed:subject=/CN=sp1.testunical.it; issuer=/CN=sp1.testunical.it; err=18; msg=self signed certificate
func=xmlSecOpenSSLEvpSignatureVerify:file=evp_signatures.c:line=370:obj=rsa-sha256:subj=unknown:error=18:data do not match:details=EVP_VerifyFinal: signature does not verify
FAIL
SignedInfo References (ok/all): 1/1
Manifests References (ok/all): 0/0
Error: failed to verify file "/tmp/tmpdq4kg5dv.xml"

output=
check_sig: ['/usr/bin/xmlsec1', '--verify', '--enabled-reference-uris', 'empty,same-doc', '--pubkey-cert-pem', '/tmp/tmp98lgcz5v.pem', '--id-attr:ID', 'urn:oasis:names:tc:SAML:2.0:protocol:AuthnRequest', '--node-id', 'id-9zdLCkuL3LHFIGyAR', '--output', '/tmp/tmpstz1_1bi.xml', '/tmp/tmpdq4kg5dv.xml']
Response was not correctly signed
````

**Comment by askvortsov1** [comment]
If this has been implemented as per your requirements, we can probably close this issue for now. We can make a note to add unit tests for this later on
