### ISSUE TITLE
[Feature Request] Management command to download, validate and store SP metadata

### ISSUE THREAD

**Issue by peppelinux** [OTA-Insight/djangosaml2idp#29]
We actually use wget/curl to download a metadata and store this in our project's relative path.
This work if the metadata file is a valid xml file, if this file is a 404 page-not-found instead, the IDP will incour in a general Exception. This will block the IDP globally in error 500.

In a real production scenario we would:
- have a list of metadata sp url and for each of them:
  - download a metadata inMemory
  - create a mdstore to validate xml
  - validate certs (if they are expired...)
  - then store as file

Some changements in settings.py would be also came, there's need of:

- a list of sp metadata download url as list of federated SP
- a brand new definition of sp metadata like follows:

````
 'metadata': [{
        "class": "saml2.mdstore.MetaDataFile",
        "metadata": [call_to_function_that_returns_a_list_of_previoously_validated_fpath_metadata()],
    }],
````

My idea is to create a django management command to accomplish this, at this moment I'm on it. 
A cron script should run this scheduled check and update. Any Ideas?

**Comment by peppelinux** [comment]
In this file we have all the test to do on a metadata:
https://github.com/IdentityPython/pysaml2/blob/master/tests/test_30_mdstore.py#L314

**Comment by askvortsov1** [comment]
Correct me if I'm wrong, but isn't there functionality for using remote metadata provided by pysaml2? https://pysaml2.readthedocs.io/en/latest/howto/config.html#metadata

I think that a management command to get remote metadata is a good idea. I believe that SimpleSamlPHP (the leading SAML2 IdP) supports dynamically generating the metadata from information about the SP. Maybe we could consider adding that in as well?

As to the function to actually get all the metadata locations, I have an alternate idea. We could provide a folder path in settings.py where all metadata would be saved. The aforementioned function would then just return paths for all XML files contained in that folder.

**Comment by peppelinux** [comment]
Yes it can download BUT if that download produce a page 404 the server goes in Internal server error when the xml was parsed.

This works also only for SP and not for IDP.
My porpose is to develop a smart management command that do the parse and also check certificate validity and availability of the endpoint.

Ok about the folder where to put all the files and a function that get them and returns as a list, as the example I tried to explain

**Comment by peppelinux** [comment]
I think that this features could be developed also as a external app, because it could be used also for djangosaml2 SP as proposed here: https://github.com/knaperek/djangosaml2/pull/104

So the idea is to develop a generic metadata downloader and verifier, on top of pySAML2 and use this in djangosaml2 or djangosaml2idp. It could also come with a utils.function that get all the stored metadata files in a folder and returns as filepath in the pysaml2's metadata list format.

Any ideas?

**Comment by askvortsov1** [comment]
I think that an external repository would work if the folks at knaperek/djangosaml2 would like this feature too.

**Comment by peppelinux** [comment]
I need it in both, sp and idp, so I'm going through this :+1:

**Comment by peppelinux** [comment]
Tests confirmed, pyff is the tool.
Once the metadata was download it can be aklso possible to serve them directly from nginx static file server this way:

````
   location ~ /entities/\{sha1\}(.*) {
      default_type "application/xml; charset=utf-8";
      alias /opt/pyff/md/$1.xml;
   }


    location ~ /entities$ {
       default_type "application/xml; charset=utf-8";
       alias /opt/pyff/md/md-loaded.xml;
    }
````

**Comment by mhindery** [comment]
As part of cleaning up some old issues, I'm going to close this. The latest version of the package stores the metadata in the db, and can refresh from a remote url.
