### ISSUE TITLE
[Additional feature] Default sign and enc algorithm for authn responses and SLO 

### ISSUE THREAD

**Issue by peppelinux** [OTA-Insight/djangosaml2idp#35]
In pySAML2 the default sign and enc algorithm is the _poor_ sha1.
I pushed a PR to get this improvement but I think that it will take a lot of time, this is here: IdentityPython/pysaml2#597

As djangosaml2 already does it we could introduce the possibility to force alternative xmlsec1 supported algs. djangosaml2 uses this method:
https://github.com/knaperek/djangosaml2/blob/master/djangosaml2/views.py#L179
In other words in pySAML2 each assertion builder method (request or response) have the sign_alg and dig_alg arguments. in djangosaml2idp we could simply put these in the call, if any sign/enc alg alternative is configured in settings.py.

There could be also this alternative as a global patch (to be tested):
knaperek/djangosaml2#115

What do you think about this? Sha1 is too weak and some federation simply rejects this.

 Styling

**Comment by askvortsov1** [comment]
I definitely agree that it would be good to replace SHA1 with something better. So just to understand your proposal for implementation, are you thinking of manually specifying the sig alg in the call to create_authn_response (https://github.com/askvortsov1/djangosaml2idp/blob/50178fe135ff79791b8807f3a17c739dcbd11eaf/djangosaml2idp/views.py#L143-L154)?

That sounds like a good idea!

**Comment by peppelinux** [comment]
Yes, and we could set it as DEFAULT and also as optionally specific for every SP. This will let us to support also an old-featured SP that, for example, support well only an algorithm.

This will let us go ahead about pySAML2 specific roadmap

**Comment by peppelinux** [comment]
Done here https://github.com/peppelinux/djangosaml2idp/commit/2f80ca73f164716fd5f0dd5630dff4644cfc6eee

It should be easy to cherry picked ;)

**Comment by askvortsov1** [comment]
Thanks! I'll be sure to cherry-pick this one out (now that I've finally figured out how to do that, sorry about this).

**Comment by mhindery** [comment]
LGTM. One comment on the linked commit: `settings.SAML_AUTHN_DIGEST_ALG` will fail if you haven't set this setting explicitly, it's better to have a default fallback.

**Comment by peppelinux** [comment]
Thank you, trivial to implement, an hasattr on settings Will do the job. I'll do on my fork and share the commit here

**Comment by mhindery** [comment]
Merged and released with version 0.6.0
