### ISSUE TITLE
[Additional Feature] Encrypted Assertions

### ISSUE THREAD

**Issue by peppelinux** [OTA-Insight/djangosaml2idp#36]
It would be better to add the possibility to encrypt the SAML assertions.
See:

https://github.com/IdentityPython/pysaml2/blob/master/src/saml2/server.py#L574
https://github.com/IdentityPython/pysaml2/blob/master/src/saml2/server.py#L675

**Comment by peppelinux** [comment]
Added here:
https://github.com/peppelinux/djangosaml2idp/commit/af69dc1edb245f0a5b32cf24cb04f822d0e8291b

needs settings parameter, works as expected!
I suggest you to implement this

**Comment by mhindery** [comment]
That is indeed a good addition, I see no drawbacks for this.

**Comment by mhindery** [comment]
merged with version 0.6.0
