### ISSUE TITLE
[Attribute Mappings] Add django mappings in example idp project

### ISSUE THREAD

**Issue by peppelinux** [OTA-Insight/djangosaml2idp#37]
See:
https://github.com/peppelinux/Django-Identity/blob/master/django-saml2-idp/django_saml2_idp/idp/saml2_config/attribute-maps/django_saml_uri.py

otherwise AttributeValue will not have FriendlyName and oid correctly valued. Some SP will reject these if not valued correctly!

This is an example of mine implementation that have many soruces, as LDAP.
You should change `uid` with `username` here:
https://github.com/peppelinux/Django-Identity/blob/master/django-saml2-idp/django_saml2_idp/idp/saml2_config/attribute-maps/django_saml_uri.py#L11

**Comment by mhindery** [comment]
As part of cleaning up some old issues, I'm going to close this. If necessary and still an issue, feel free to reopen.
