### ISSUE TITLE
[Security] IDP shouldn't answer to SP saml request with unsupported name ID formats

### ISSUE THREAD

**Issue by peppelinux** [OTA-Insight/djangosaml2idp#38]
in https://github.com/OTA-Insight/djangosaml2idp/blob/master/djangosaml2idp/views.py#L232
or in https://github.com/askvortsov1/djangosaml2idp/blob/master/djangosaml2idp/views.py#L146

The IDP return an UNSPECIFIED format if neither the sp or the idp nameid format was found.
In addition, a check about the availability of the requested name id format, idp side, hasn't been made.

This should raise an handled exception

**Comment by mhindery** [comment]
This was merged and released with version 0.6.0
