### ISSUE TITLE
Trying to intgrate with AWS cognito

### ISSUE THREAD

**Issue by vaibhav-jain** [OTA-Insight/djangosaml2idp#43]
Getting error on Successful login

```
UnknownSystemEntity at /idp/login/process/
urn:amazon:cognito:sp:us-east-2_KstJKAXym
```

![image](https://user-images.githubusercontent.com/4224414/57017115-3e8fea00-6c3b-11e9-9bf6-04f6f7ee44cd.png)

I know it might be out of scope for this package as it is not mentioned anywhere that it is for AWS. But I am hoping you can point me out in the right direction as SAML is quite new for me.

Thanks

**Comment by peppelinux** [comment]
Unknown systementity... Is its Metadata loaded in idp settings?

**Comment by vaibhav-jain** [comment]
@peppelinux 

PFA screenshot 

![image](https://user-images.githubusercontent.com/4224414/57020038-c67af180-6c45-11e9-9b42-ca057df1c650.png)

I have uploaded idp metadata XML on the AWS console

**Comment by peppelinux** [comment]
What's the entityID written in idp metadata? Probably aws needs some metadata customizations, never used It but we can investigate with your help

**Comment by vaibhav-jain** [comment]
SP: entityID="http://localhost:8000/saml2/metadata/"
IDP: entityID="http://localhost:9000/idp/metadata"

**Comment by peppelinux** [comment]
I suggest you ti use fqdn to have a real unique entity_id for each SP or idp. Question: would aws be a SP of your idp?

**Comment by vaibhav-jain** [comment]
Actually, we want to be both is it possible?

we will have a separate server for idp
and different app servers for SP

**Comment by vaibhav-jain** [comment]
@peppelinux if you have free time we can work on this together by connecting remotely

**Comment by peppelinux** [comment]
Is AWS metadata loaded into your idp settings.py?

**Comment by vaibhav-jain** [comment]
Nope, how can I do that? please let me know

**Comment by peppelinux** [comment]
Please consult AWS SAML2 official documentation, by the way I found this:
https://signin.aws.amazon.com/static/saml-metadata.xml

**Comment by vaibhav-jain** [comment]
you want me to set  
```
   'metadata': {
        'local': [os.path.join(os.path.join(os.path.join(BASE_DIR, 'idp'), 'saml2_config'), 'sp_metadata.xml')],
    },
```
?

**Comment by vaibhav-jain** [comment]
Tried replacing SP metadata XML given in the idp app but no luck

**Comment by peppelinux** [comment]
the SP entityID would be:
urn:amazon:cognito:sp:us-east-2_KstJKAXym

in the previous link I read `urn:amazon:webservices`

**Comment by vaibhav-jain** [comment]
Getting SAMLError at /idp/login/process/
Unknown entity or unsupported bindings

![image](https://user-images.githubusercontent.com/4224414/57026929-9557ec80-6c58-11e9-83f8-d46e95b157d3.png)

**Comment by Amertz08** [comment]
I'm actually having to work on this too. AWS is expecting certain assertions on the Authentication Response per [docs](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_saml_assertions.html). However I am struggling to figure out what I need to do in order to achieve this. Been poking around Pysaml2 `server.Server.create_authn_response` and the IDPs usage.
