### ISSUE TITLE
Feature request: Allow SP configurations to load from database models.

### ISSUE THREAD

**Issue by singhravi1** [OTA-Insight/djangosaml2idp#50]
Can we please use models to load service providers configurations `SAML_IDP_SPCONFIG` from models which will make them dynamic?
we can save the xml metadata directly in the database instead of files.

**Comment by peppelinux** [comment]
Done here:
https://github.com/UniversitaDellaCalabria/uniAuth

metadata and sp can be configured through Admin UI
uniAuth is a djangosaml2idp fork

**Comment by singhravi1** [comment]
Wow! Thanks a lot for this.

**Comment by peppelinux** [comment]
please put a star ;)

**Comment by askvortsov1** [comment]
@mhindery would you be interested in cherry-picking any of these features to this library?

**Comment by peppelinux** [comment]
uniAuth is at this moment a quite extended project, I don't think that cherry-picking could be adopted.
A lot of commits made uniAuth different from djangosaml2idp in its core.
As you can see uniAuth come like a standalone and quite monolithic project but we could think to decouple from this a standalone app (uniauth core) and create a brand new project or a new main release of djangosaml2idp.

uniAuth have some important standards, like full forceauth support, allowcreate and an automatic policy system that releases the only the attributes requested from the SP. They should be defined in sp metadata.

It also have some additional features.
I included @mhindery in the apache2 license and thanks to @askvortsov1 in the documentation.
I need some stability and fast response time in the uniauth development.
If you think that we could do something together I'm quite opened to any purposes of yours.

**Comment by mhindery** [comment]
@askvortsov1 which specific features would you be interested in having in djangosaml2idp (besides the loading of config via models instead of settings / on-disk files)?

**Comment by peppelinux** [comment]
woudn't it be better to put them all in a new milestone?
nameid format could be another I think

**Comment by singhravi1** [comment]
Guys, this gentleman has implemented the model based SP configuration [here](https://github.com/mikeclarke/djangosaml2idp). Maybe we can ask him to merge his fork.

**Comment by peppelinux** [comment]
this is my approach:
https://github.com/UniversitaDellaCalabria/uniAuth/blob/master/uniauth/models.py#L45

you can even disable an SP even if you auto accept it from its metadata presence, see uniauth's `DISABLE_UNSPECIFIED_SP`

**Comment by mhindery** [comment]
I've been working on this on a feature branch: https://github.com/OTA-Insight/djangosaml2idp/pull/51 The code is functional, but there are some things that need to be done still; adapt the documentation for it, and adapt the included demo setup for the database-backed setup.
