### ISSUE TITLE
[Bug] get_nameid_email() got an unexpected keyword argument 'sp_entityid'

### ISSUE THREAD

**Issue by sarthakk97** [OTA-Insight/djangosaml2idp#52]
I get the following error when I try an SP initiated login.

`[djangosaml2idp.views] [views.py:90] {'exception': TypeError("get_nameid_email() got an unexpected keyword argument 'sp_entityid'",), 'status': 500}`

This issue seems to be because `kwargs` is passed to the `get_nameid_email`( callback function returned by `getattr` ) in line 73. The `get_nameid_email` function definition does not specify `kwargs` as a parameter.

**Comment by mhindery** [comment]
I've published a bugfix release v0.6.2 to pypi which fixes this issue.
