### ISSUE TITLE
Persistent ID

### ISSUE THREAD

**Issue by askvortsov1** [OTA-Insight/djangosaml2idp#62]
In some cases, I feel like having a persistent ID could be valuable. @mhindery Wanted to run my idea for execution by you before making a PR:

1. Set up a PersistentID model that has a OneToOne relationship with the AUTH_USER model
2. If NAMEID is requested to be Persistent, check if the user has a persistentid. If so, send that. If not, make a new one, with the actual persistentid being a randomly generated uuid.

**Comment by peppelinux** [comment]
It could also depends by allow create, see uniAuth for backreference 😜

**Comment by askvortsov1** [comment]
Addressed in #65
