### ISSUE TITLE
Custom Processors not working

### ISSUE THREAD

**Issue by sarthakk97** [OTA-Insight/djangosaml2idp#63]
We need to send a few additional attributes in our usecase. However , we seem to be getting a crash when we use a custom processor. Additionally , only the username attribute is present in the   SAML response. Could you look into this? I see that there's a recent commit that I believe addresses this issue. 

If I'm right , could you fast track the process and make the latest release soon? We would really appreciate it. Thanks!

**Comment by mhindery** [comment]
Hi @sarthakk97 , I've pushed v0.6.3 to pypi, which has as only change this MR: https://github.com/OTA-Insight/djangosaml2idp/pull/61/files If that doesn't solve your issue, could you give a little bit more info about what you are doing and what is going wrong? Some code to replicate it (if possible using the example setup included as that's easily set up on my side as well) and a stacktrace or error message you're getting.

**Comment by mhindery** [comment]
Hi @sarthakk97 , I'm going to close this issue as I did not get any reply, so there is nothing to do here. Let us know if you still cannot get this to work (preferably with the latest release).
