### ISSUE TITLE
No module named 'djangosaml2idp'

### ISSUE THREAD

**Issue by Touzi-Mortadha** [OTA-Insight/djangosaml2idp#81]
I tried to run `docker-compose up` for the example setup but i get this error:

> djangosaml2idp_idp exited with code 1
> djangosaml2idp_idp | Traceback (most recent call last):
> djangosaml2idp_idp |   File "manage.py", line 22, in <module>
> djangosaml2idp_idp |     execute_from_command_line(sys.argv)
> djangosaml2idp_idp |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
> djangosaml2idp_idp |     utility.execute()
> djangosaml2idp_idp |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
> djangosaml2idp_idp |     django.setup()
> djangosaml2idp_idp |   File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
> djangosaml2idp_idp |     apps.populate(settings.INSTALLED_APPS)
> djangosaml2idp_idp |   File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
> djangosaml2idp_idp |     app_config = AppConfig.create(entry)
> djangosaml2idp_idp |   File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
> djangosaml2idp_idp |     module = import_module(entry)
> djangosaml2idp_idp |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
> djangosaml2idp_idp |     return _bootstrap._gcd_import(name[level:], package, level)
> djangosaml2idp_idp |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
> djangosaml2idp_idp |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
> djangosaml2idp_idp |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
> djangosaml2idp_idp | ModuleNotFoundError: No module named 'djangosaml2idp'

**Comment by mhindery** [comment]
This was due to a symlink between the example setup and the package python code, which didn't mount correctly in Docker, so the source code for that application could not be found. It has been updated (the base image has been updated as well in the linked MR but that is not relevant for this issue), and works again (confirmed by me that it works locally and the login flow is succesful)
