### ISSUE TITLE
How can I create sp_metadata.xml? 

### ISSUE THREAD

**Issue by bendavis78** [OTA-Insight/djangosaml2idp#85]
I can't find any documentation on creating sp_metadata.xml. Is there a tool for generating this?

**Comment by Amertz08** [comment]
Generating that is a responsibility of the service provider implementation. The example service provider implementation should provide the [URLs](https://github.com/OTA-Insight/djangosaml2idp/blob/master/example_setup/sp/sp/urls.py#L10) for doing that. Follow that link back to `djangosaml2` urls file and there should be a metadata view. Visit that url when running your service provider to download the XML file. You'll then place that XML file in your IDP metadata config directory. You'll also want to visit the IDP metadata URL and download the IDP XML file and place it in the SP's metadata config directory.

**Comment by mhindery** [comment]
Going to close this issue, as there is nothing to do. As Adam mentioned, this is something which the packages will provide for you, and you get it simply by visiting the necessary url. The example setup contains an idp implemented with djangosaml2idp, and an sp implemented with djangosaml2, which both have a `/metadata/` url which returns the xml file you're looking for. Some further information can also be found in the [djangosaml2 documentation](https://github.com/knaperek/djangosaml2#idp-setup)
