### ISSUE TITLE
Importing issue

### ISSUE THREAD

**Issue by alaalqadi** [OTA-Insight/djangosaml2idp#94]
@mhindery 
Hello, I'm trying to import ServiceProvider into my project, but when I do the following:
from djangosaml2idp.models import *
the following error happens
ImportError: No module named models, Any idea what's happening here?
Also, there's no file named models.py in the path after I do pip install djangosaml2idp, your help will be highly appreciated.

**Comment by mhindery** [comment]
When you run `pip freeze`, which version is reported to be installed? I suspect you already have a previous version of the package installed (or it has selected that one to install), which does not have the models yet. You can either do `pip install --upgrade djangosaml2idp` which should fetch the latest available, or explicitly specify the version with `pip install djangosaml2idp==0.7.1`

**Comment by alaalqadi** [comment]
I'm using djangosaml2idp==0.3.3, python 2.7 and Django 1.8.6

**Comment by askvortsov1** [comment]
The recent changes with models are only available in v 0.7 and up I believe. We also no longer support python 2.6 and versions of Django below 2.2

**Comment by alaalqadi** [comment]
Okay, I was wondering if you have docs maybe for the older versions?

**Comment by alaalqadi** [comment]
And can I add the for example the metadata url in the configs, something like this 
   'metadata_url': 'url_goes_here',
   'attribute_mapping': {
            # Django Model Attribute:  SAML2 Attributes
            'username': '%s/externalID' % EF_SCHEMA_URL,
            'email': '%s/emailaddress' % EF_SCHEMA_URL,
            'first_name': '%s/givenname' % EF_SCHEMA_URL,
            'last_name': '%s/surnamed' % EF_SCHEMA_URL,
            'get_country_name': '%s/country' % EF_SCHEMA_URL,
        }

**Comment by mhindery** [comment]
First of all, I'd really urge you to update that setup. The Django version you are running is out of (even extended) support for 2 years now, and you are missing out on a lot of updates with bugfixes, features and security issues being handled. As far as any documentation for the old version of the package goes, you can browser the package at that point in time: https://github.com/OTA-Insight/djangosaml2idp/tree/160c1b1f7c398b16285f61fadcc76caad6740663 The readme contains how to use this. I can't really speak what will or won't work for that old one. Remote metadata was not supported back then yet, and also the redirect method was not supported, only post.

**Comment by alaalqadi** [comment]
Unfortunately updating the setup is not an option in the meantime, but after doing some digging and re-configuration, now i'm blocked by this error ERROR:saml2.request:Response was not correctly signed
can you help or do you have any idea what's causing it?

**Comment by mhindery** [comment]
That would mean that either there is a mismatch in configuration between the idp and the sp, for example the idp requires some messages to be signed and the sp thinks it does not, so it doesn't include the necessary signature. This can also be the signing certificate being different between the metadata which the idp has, and which the sp is using.

**Comment by alaalqadi** [comment]
I tried  https://github.com/OTA-Insight/djangosaml2idp/tree/160c1b1f7c398b16285f61fadcc76caad6740663
but there are so many errors in it, for example:
IndexError at /saml2/login/
pop from empty list'

**Comment by alaalqadi** [comment]
so is there any newer version related to this? or that's it ?

**Comment by askvortsov1** [comment]
This project has received quite a bit of work over the past year or so, but most of those changes were made considering advances in underlying libraries. At this point, both that version of Django and of python are past their end of support. I don't believe that djangosaml2idp intends to support those versions, or rewrite the recent changes to work with those versions. However, this being an open source project, you are more than welcome to fork the repo, and modify it so that the current version will be compatible with your environment.

**Comment by alaalqadi** [comment]
Thank you, my friend, for your support, I'm good now I managed to make it work

**Comment by alaalqadi** [comment]
Sorry guys, but I'm not able to use the service without certificates, Any idea?

**Comment by mhindery** [comment]
Certificates are something that you need to provide yourself, and depends on what you are running. Those can be self-signed certificates you generate, or other SSL certificates for the systems you are using.
